//
//  BrickExample.swift
//  AppDeveloperKit-Library
//
//  Created by Scott Carter on 11/21/17.
//

import UIKit

import AppDeveloperKit


// An example of subclassing a Library component (BrickBaseViewController) in order to provide a custom
// configuration.  Why might you do this?
//
// You may wish to use a Library component for different screens, but customize the appearance of
// each of the screens.
//
class BrickExample: BrickBaseViewController {

    // Can call adk_deinitBrickExample() from overriden func adk_deinit() or alternatively from
    // deinit.  Could also safely call adk_deinitBrickExample() from both places, though only the first
    // call has any effect.
    
    deinit {
//        adk_deinitBrickExample()
    }
    
    override func adk_deinit() {
        adk_deinitBrickExample()
    }
    
    override func adk_init() {
        adk_initBrickExample()
    }
    
}


// AppDeveloperKit configuration methods.
// They can be autogenerated and included in AppDeveloperKit.swift, or manually inserted as shown here.
//
extension BrickExample {
    
    func adk_deinitBrickExample() {
        
        let adk = ADK_Config.shared()
        
        adk.deregisterClass(sender: self)
    }
    
    func adk_initBrickExample() {
        
        let adk = ADK_Config.shared()
        
        weak var weakSelf: BrickExample? = self
        
        adk.registerClass(sender: self, name: "BrickExample")
        
        
        adk.configBool(sender: self, name: "horizontal", initComplete: { (data) in
            if data != nil {
                weakSelf?._horizontal = data!
            }
        }, changeComplete: { (data) in
            if data != nil {
                weakSelf?.horizontal = data!
            }
        })
        
        
        adk.configJSON(sender: self, name: "json", initComplete: { (data) in
            if data != nil {
                weakSelf?._json = data!
            }
        }, changeComplete: { (data) in
            if data != nil {
                weakSelf?.json = data!
            }
        })
        
        
    }
}


